name: Claude PR Review

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-3-5-sonnet-latest
          # اختياري — فعّلي ما تحتاجينه فقط:
          summarize: true
          inline_suggestions: true
          # path_filters: |
          #   app/**.py
          # focus: security
          # patch_only: true
