name: Claude Assistant

on:
  workflow_call:
    inputs:
      additional_context:
        type: string
        required: false
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  assistant:
    if: |
      github.event_name == 'workflow_call' ||
      startsWith(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Resolve prompt
        id: prompt
        uses: actions/github-script@v7
        env:
          BODY: ${{ github.event.comment.body || inputs.additional_context || '' }}
        with:
          script: |
            const body = (process.env.BODY || '').replace(/^@claude\s*/,'').trim();
            core.setOutput('prompt', body || 'Summarize the latest changes in this PR and suggest improvements.');

      - name: Call Anthropic Messages API
        id: call
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          PROMPT: ${{ steps.prompt.outputs.prompt }}
        run: |
          echo '{"model":"claude-3-5-sonnet-latest","max_tokens":800,"messages":[{"role":"user","content":"'"$PROMPT"'"}]}' > body.json
          curl -s https://api.anthropic.com/v1/messages \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d @body.json > resp.json
          cat resp.json | jq -r '.content[0].text' > out.txt || echo "No response" > out.txt

      - name: Post reply
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('out.txt','utf8').trim();
            const issue_number = context.payload.issue?.number || context.payload.pull_request?.number || context.payload.workflow_call?.inputs?.issue_number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number || (context.payload.pull_request?.number ?? context.issue.number),
              body
            });
