name: Claude Dispatch

on:
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  debugger:
    if: ${{ fromJSON(vars.DEBUG || vars.ACTIONS_STEP_DEBUG || false) }}
    runs-on: ubuntu-latest
    steps:
      - name: Print event debug
        env:
          DEBUG_event_name: ${{ github.event_name }}
          DEBUG_event_action: ${{ github.event.action }}
          DEBUG_event: ${{ toJSON(github.event) }}
        run: |
          env | grep '^DEBUG_'

  dispatch:
    # PRs: فقط لو مو من fork
    # التعليقات: فقط لو تبدأ بـ @claude أو /review ومن OWNER/MEMBER/COLLABORATOR
    if: |
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.fork == false)
      || (
        github.event.sender.type == 'User' &&
        startsWith(github.event.comment.body || github.event.review.body || github.event.issue.body, '@claude')
        && contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'),
                    github.event.comment.author_association || github.event.review.author_association || github.event.issue.author_association)
      )
      || (
        github.event.sender.type == 'User' &&
        startsWith(github.event.comment.body || github.event.review.body || github.event.issue.body, '/review')
      )
      || (
        github.event_name == 'issues' &&
        contains(fromJSON('["opened","reopened"]'), github.event.action)
      )
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.extract.outputs.command }}
      additional_context: ${{ steps.extract.outputs.additional_context }}
      issue_number: ${{ github.event.pull_request.number || github.event.issue.number }}
    steps:
      - name: Extract command
        id: extract
        uses: actions/github-script@v7
        env:
          EVENT_TYPE: ${{ github.event_name }}.${{ github.event.action }}
          REQUEST: ${{ github.event.comment.body || github.event.review.body || github.event.issue.body || '' }}
        with:
          script: |
            const req = (process.env.REQUEST || '').trim();
            const evt = process.env.EVENT_TYPE || '';
            core.setOutput('additional_context', req);

            if (req.startsWith('@claude /review') || req.startsWith('/review') || evt === 'pull_request.opened') {
              core.setOutput('command', 'review');
            } else if (req.startsWith('@claude')) {
              core.setOutput('command', 'assistant');
            } else if (['issues.opened','issues.reopened'].includes(evt)) {
              core.setOutput('command', 'triage');
            } else {
              core.setOutput('command', 'fallthrough');
            }

      - name: Acknowledge request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || github.token }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          MSG="🤖 Hi @${{ github.actor }}, I've received your request. Track progress [in the logs](${RUN_URL})."
          curl -sL -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${GITHUB_TOKEN}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
           -d "{\"body\":\"${MSG}\"}"

  review:
    needs: dispatch
    if: ${{ needs.dispatch.outputs.command == 'review' }}
    uses: ./.github/workflows/claude-review.yml
    secrets: inherit

  assistant:
    needs: dispatch
    if: ${{ needs.dispatch.outputs.command == 'assistant' }}
    uses: ./.github/workflows/claude-assistant.yml
    with:
      additional_context: ${{ needs.dispatch.outputs.additional_context }}
    secrets: inherit

  triage:
    needs: dispatch
    if: ${{ needs.dispatch.outputs.command == 'triage' }}
    uses: ./.github/workflows/claude-triage.yml
    secrets: inherit

  fallthrough:
    needs: [dispatch, review, assistant, triage]
    if: ${{ always() && !cancelled() && (failure() || needs.dispatch.outputs.command == 'fallthrough') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || github.token }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
        run: |
          MSG="🤖 Sorry @${{ github.actor }}, I couldn't process that command. See the logs for details."
          curl -sL -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${GITHUB_TOKEN}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
           -d "{\"body\":\"${MSG}\"}"
